# Generated by Django 2.2.1 on 2019-05-04 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(default='작성하지 않음', max_length=200)),
                ('event', models.CharField(default='작성하지 않음', max_length=200)),
                ('event_id', models.IntegerField(default=0)),
                ('place', models.CharField(default='작성하지 않음', max_length=200)),
                ('time_start', models.TimeField(default=django.utils.timezone.now)),
                ('time_end', models.TimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('code', models.CharField(choices=[('A', 'Activity'), ('C', 'Concert'), ('선택하지 않음', '----')], default='선택하지 않음', max_length=200)),
                ('date', models.IntegerField(default=0)),
            ],
        ),
    ]
